version: "3.1"
services:
  seata-server:
    image: seataio/seata-server:1.5.2
    ports:
      - "7091:7091"
      - "8091:8091"
    links: #在nacos-docker/example/里面跑这个了
      - nacos
      - mysql
    environment:
      - STORE_MODE=db
      # 以SEATA_IP作为host注册seata server
      - SEATA_IP=local.seata.server
      - SEATA_PORT=8091
    volumes:
      - "/d/anel/github/awesome-seata/seata-server/resources:/seata-server/resources"